name: weather_tracker

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For ios icons
  cupertino_icons: ^1.0.2

  # For getting lat log
  geolocator: ^8.2.1

  # For using apis
  http: ^0.13.4

  # For rotating spining animation
  flutter_spinkit: ^5.1.0

  # For showing toast
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "icon/cloudy.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true
#   web:
#     generate: true
#     image_path: "icon/cloudy.png"
#   windows:
#     generate: true
#     image_path: "icon/cloudy.png"
#   macos:
#     generate: true
#     image_path: "icon/cloudy.png"

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
